### ISSUE TITLE
タグを追加した表示がおかしい

### ISSUE THREAD

**Issue by rikusen0335** [setsunaMC/flarum-ext-japanese#3]
![SnapCrab_NoName_2019-7-8_20-23-43_No-00](https://user-images.githubusercontent.com/19174234/60806622-7167d880-a1be-11e9-9c16-19c9bbddca54.png)
上記のような感じで、タグを追加したときに「タグ」が2つ入ってます。

**Comment by n04h** [comment]
ご利用ありがとうございます！
Flarumのバージョンが`v0.1.0-beta8`で確認したのですが、
どの画面が該当するのかわからなかったので、
下記部分についてもう少し詳細を教えていただけますか？
- Flarumのバージョン
- タグを追加する画面

**Comment by rikusen0335** [comment]
申し訳ありません、情報が抜けてました
FlarumはBeta9ですが、8でも確認できました。
具体的には、`flarum-tags.yml`の`post_stream.added_tags_text`がだめっぽいです
もしかすると他のタグ系もだめかも知れませんが、そっちは検証してないのでまだわからない状態です

**Comment by n04h** [comment]
該当する場所を確認できました。
修正しましたので、`composer require n04h/flarum-ext-japanese`をして更新をお願いします。
問題が解決しましたら、クローズをお願いします。
この度はありがとうございました！

**Comment by rikusen0335** [comment]
`added_and_removed_tags_text`、 `removed_tags_text`もちょっとおかしいです。

**Comment by n04h** [comment]
ありがとうございます！
修正しましたので、アップデートをし確認をお願いします。
